### ISSUE TITLE
An item with the same key has already been added. Key: Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadata

### ISSUE THREAD

**Issue by atefboujday** [sgjsakura/AspNetCore#23]
I Create a new solution with VS 2017. My solution contain the following project

1- Application.models (Class Library DotNetCore)
Reference : Sakura.AspNetCore.Mvc.PagedList (2.0.12) AND Sakura.AspNetCore.PagedList
My Model is: 
using Sakura.AspNetCore;
using System;

namespace Hospea.Model
{
    public class DetailModel
    {
        public int DetailId { get; set; }
        public string DetailNumber { get; set; }
    }

    public class SearchModel
    {

        public string CustomerName { get; set; }
        public int? Page { get; set; }
        public string SortColumn { get; set; }
        public string Direction { get; set; }

        public string SortExpression
        {
            get
            {
                return string.IsNullOrEmpty(SortColumn) ? string.Empty
                           : string.Format("{0} {1}", SortColumn, Direction);
            }
        }
        public string SearchButton { get; set; }

        public IPagedList<DetailModel> Details { get; set; }
    }
}

2- A second project Application.DataAccess  (Class Library DotNetCore)
 reference to : Application.Model

contain a function that return IEnumerable<DetailModel>

3- Application.Web (Application Web Asp .Net Core (.netCore)
Reference Application.DataAccess
Contain a controller with action :
public IActionResult Index(SearchModel model)
{
                return View(model);
}

When I run my application and try to run my action, i have the error

An item with the same key has already been added. Key: Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadata

**Comment by sgjsakura** [comment]
@atefboujday Hi, thank you for your reply, this problem is caused by the MVC model binding system, for detailed information, you may refer to #15.

Hope it helps, and please feel free to reply if you have any new question.

**Comment by atefboujday** [comment]
@sgjsakura thank for your reply. Can you explain where is exactly my problem

**Comment by sgjsakura** [comment]
@atefboujday Internally, MVC model binding system can build model with primitive values, POCO objects, and indexed collections (e.g. array or `List<T>`). For non-primitive values, any type references by the model and/or it submodels must has a public zero-argument constructor. However, the `IPagedList<T>` class is an interface type and cannot be initialized, and the index-based assignment will cause errors. 

To fixed this problem, you may remove the `Details` property from your input model (the argument received by an controller action, while the display model passed by the `View` method is not affected), because it is not supported by MVC.

**Comment by atefboujday** [comment]
@sgjsakura, this problem is just comes from with dotnet core? Because with vs 2013, i worked always with search models that contain a IPagedList property.

**Comment by sgjsakura** [comment]
@atefboujday The error is caused by the MVC Core and the exception can be considered as a BUG. You may simply update your project to .NET Core 1.1, the `Details` property will be `null` since it cannot be intiailized, however the exception will no longer occur and your MVC action can been executed normally.

**Comment by atefboujday** [comment]
@sgjsakura, my solution was created with VS 2017, so i automatically use .Net Core 1.1.

**Comment by sgjsakura** [comment]
@atefboujday No, even you are using VS 2017, the default .NET Core version will still be .NET Core 1.0. You may change the .NET Core version in your project property page.

**Comment by atefboujday** [comment]
@sgjsakura bizarre

![capture](https://cloud.githubusercontent.com/assets/6393700/24464204/6eb956f8-14a9-11e7-8122-db24e0f0b202.PNG)

**Comment by sgjsakura** [comment]
@atefboujday Thank you for your feedback. Please make a double check if the `Microsoft.AspNetCore.Mvc` package in your project (can be viewed in "manage nuget packages" menu item) is in version 1.1.0 or higher. And if the project are still using the version of 1.0.x, you may upgrade it to the lastest version.

Hope it helps. :-)

**Comment by atefboujday** [comment]
@sgjsakura.
![capture2](https://cloud.githubusercontent.com/assets/6393700/24464573/95436132-14aa-11e7-91cd-f991b600ba27.PNG)

**Comment by sgjsakura** [comment]
@atefboujday Hi, thank you for your feedback, since in #15 it is reported that the exception will not occur when the package is updated to 1.1.0, I should take more test to check the actual response in this snece.

Nevertheless, put an `IPagedList<T>` in your the argument model is always not valid due to the principle of MVC binding system. As walkaround and best practise, it is suggested to remove this property in your argument model. You may use type inheritances to generate models for both input and display. A simple example can be the following:
```C#
public class SearchInputModel
{
   // Only input datas (e.g. search text) comes from user
}

public class SearchDisplayModel : SearchInputModel
{
   // Add any data used in View such as search result
}

// The argument of the action can only receive user inputs, thus input model should be used
public IActionResult Search(SearchInputModel model)
{
   var displayModel = new SearchDisplayModel();
   // Custom operations.

   // Display model contains additional data used in view.
   return View(displayModel); 
}

```

Hope it helps :-)

**Comment by atefboujday** [comment]
@sgjsakura, thank you for your reply. Taht exactly what i did before posting my question. Hope that the bug wil be fixed very soon.

**Comment by sgjsakura** [comment]
@atefboujday Hi,  this problem is confirmed and fixed. It is caused by incorrect handling for interface types with multiple base interfaces with same member names.

You may update `Sakura.AspNetCore.PagedList` to the lastest version of `2.0.2` or manually isntall the dependent internal package `Sakura.AspNetCore.PagedList.Abstractions` with version `2.0.1` to fix this problem.

Thank you again for your feedback and please fill free to reply if you have any new question.
