### ISSUE TITLE
Pager is appending extra links after click

### ISSUE THREAD

**Issue by Naturesromance** [sgjsakura/AspNetCore#24]
I am using the pager for 67 pages.  The pager initially displays with 1 2 3 ... 65 66 67.  When I click on the page 3 link, the pager is now 1 2 3 4 5 ... 65 66 67.  If I then click on page 65 link, the pager is 1 2 3 ... 63 64 65 66 67.

I know there must be something simple that I am missing but I have been racking my brain for the last day and half.  Any help would be greatly appreciated.

**Comment by sgjsakura** [comment]
@Naturesromance Hi, thank you for your feedback. Defaultly, the pager will show 3 items in both starting and ending, the current page item, and 2 extra items in both left and right side for current page. The effect described in your issue seems work correctly, and could you tell me what's the exact effect you want in your application?

Hope for your kind reply :-)

**Comment by Naturesromance** [comment]
Thank you for your quick response.  I am wondering if the following example is correct behavior.  First I click on page 3. Next I click on page 4.  The result is 1 2 3 4 5 6 ... 65 66 67.  I assumed that it would be displayed as ... 2 3 4 5 6 ... 65 66 67.  I thought there should only be two pages left of the active page 4.

![pager](https://cloud.githubusercontent.com/assets/20227913/25016767/1cd6a154-2036-11e7-9029-f50e03abdda4.png)

**Comment by sgjsakura** [comment]
@Naturesromance Actually, as the default setting, the pager will try to display 3 ending pages for both side (1,2,3 65,66,67), the current page (4), and 2 extra pages in both side (2,3,5,6). The final merged result just looks as your supplied image below, and the pager is working correctly. 

If you want to chagne the page number to show in ending and/or current page, you may change the `PagerOptions`, for more information, please read the documentation and feel free to open new issues if you have any question.

I'm closing this issue since there is no incorrect behavior.
