### ISSUE TITLE
Paging custom parameters

### ISSUE THREAD

**Issue by yujiajunbmj** [sgjsakura/AspNetCore#30]
The custom parameter set by page label setting-tagname="C#" is invalid when paging, and the controller cannot get the tagname

**Comment by yujiajunbmj** [comment]
page
`<pager setting-tagname="C#" />`
global
`public void ConfigureServices(IServiceCollection services)
{
  services.AddBootstrapPagerGenerator(options =>
  {
    // Use default pager options.
    options.ConfigureDefault();
   });
}
`
action
`public IActionResult DataPager(string tagname,int page)
{
     
} `
The tagname does not get the parameter value
I don't know if I have any other configuration wrong?
Thank you for your reply.

**Comment by sgjsakura** [comment]
@yujiajunbmj HI, thank you for your reply. It seems that you are trying to customize the generated link URL format (Actually a custom action argument is just a part of URL query string). In order to do this, currently you should provide a custom link generator, a sample may like the following code:
```HTML
<pager setting-item-default-link="PagerItemLinkGenerators.Custom((int page) => Url.Action("MyAction", "MyController", new { page = page, tagname = "C#" }))" />
```
Note that the link generator is just a method instance with type like `Func<int, string>` where the argument is the page number and the result is the final link URL. You can use any other custom delegated methdo to generate your link as you wish.

Hope this helps, and if you have any further quesion, please feel free to reply here.

**Comment by yujiajunbmj** [comment]
Thank you very much for your reply. My problem has been solved smoothly
