### ISSUE TITLE
Sakura.AspNetCore doesnot contains defination of to ToPagedList<>

### ISSUE THREAD

**Issue by ermithun** [sgjsakura/AspNetCore#7]
Error	CS1061: **'IQueryable<Products>' does not contain a definition for 'ToPagedList' and no extension method 'ToPagedList' accepting a first argument of type 'IQueryable<Products>' could be found (are you missing a using directive or an assembly reference?)	NETCoreApp,Version=v1.0**	

````
 public async Task<IActionResult> Index(int? page, int? pageSize)
        {
            int no = page ?? 1;
            int size = pageSize ?? 3;
            var data = from i in _context.Products select i;
            IPagedList<Products>lst= data.ToPagedList(size, no);
            return View(lst);
        }`
```

I have install package
   "Sakura.AspNetCore.PagedList.Abstractions": "1.0.1",
    "Sakura.AspNetCore.Mvc.PagedList": "2.0.2"
in my project

**Comment by sgjsakura** [comment]
@ermithun Hi, Thank you for your feedback. In order to generate instances of `IPagedList` interface, you should add the package `Sakura.AspNetCore.PagedList` (note it is a seperate library different with `Sakura.AspNetCore.Mvc.PagedList`) and add a using directive `using namespace Sakura.AspNetCore;` in your file.

**Comment by ermithun** [comment]
@sgjsakura  Thankyou :+1:

**Comment by sgjsakura** [comment]
It seems this problem has been resolved. Closing this issue. Please feel free to reopen it if you have any new problem.
