### ISSUE TITLE
Sakura.AspNetCore  ajax pager tag helper?

### ISSUE THREAD

**Issue by ermithun** [sgjsakura/AspNetCore#8]
how to use ajax pager in AspNet core 1.0 ??
in RC1 i had done this , it worked.
     `<nav asp-pager="@Model" data-ajax-method="GET" data-ajax-update="#replace-search-data"></nav>`

But
in AspNet core 1.0 I m Trying this but it doesnot work

` <pager source="@Model" data-ajax="true" data-ajax-method="GET" data-ajax-update="#replace-search-data" />`

**Comment by sgjsakura** [comment]
@ermithun HI, the new version 2.0 of `Sakura.AspNetCore.Mvc.PagedList` used a new tag processing model, thus custom HTML attrbiutes on `<pager>` element will not work. 

In order to set addtional attributes for pagers, the pager genreator service must support this feature. Fortunately, the default implementation does support it. In your case, you may use `setting-link-attr-*` attributes to add attributes on the generated `<a>` element. e.g. Your problem can be solved using the following code:
```HTML
<pager source="@Model" setting-link-attr-data-ajax="true" setting-link-attr-data-ajax-method="GET" setting-link-attr-data-ajax-update="#replace-search-data" />
```
 For detailed introduction, please see the `Customization for Default Implementation` section in the [Pager Demo](https://github.com/sgjsakura/AspNetCore/blob/master/PagerDemo.md) page.

Hope it helps, and thank you for you feedback :-)

**Comment by ermithun** [comment]
@sgjsakura  Thankyou for  support :+1:

**Comment by sgjsakura** [comment]
Closing this issue since it seems be solved. Please feel free to reopen it if you have any new problem.
